// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("../src/App.js");
var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var ReactTestingLibrary = require("@rescriptbr/react-testing-library/src/ReactTestingLibrary.js");

Jest.describe("App", (function (param) {
        Jest.test("renders", (function (param) {
                return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(App.make, {}))));
              }));
        return Jest.test("contains `It works!`", (function (param) {
                      var partial_arg = {
                        NAME: "Str",
                        VAL: "It works!"
                      };
                      var arg = function (param, param$1) {
                        return ReactTestingLibrary.getByText(partial_arg, param, param$1);
                      };
                      return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(Curry._2(arg, undefined, ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(App.make, {})))));
                    }));
      }));

var it = Jest.test;

exports.it = it;
/*  Not a pure module */
