// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  return React.createElement(React.StrictMode, {
              children: React.createElement("h1", undefined, "It works!")
            });
}

var make = App;

exports.make = make;
/* react Not a pure module */
