// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.js");
var React = require("react");
var ReactDom = require("react-dom");

var node = document.querySelector("#root");

if (node == null) {
  console.log("There was an error finding the `#root` node.");
} else {
  ReactDom.render(React.createElement(App.make, {}), node);
}

/* node Not a pure module */
